package com.softropic.payam.mtn.service;

import com.softropic.payam.common.payment.MobileMoneyPort;
import com.softropic.payam.common.payment.PaymentCommand;
import com.softropic.payam.common.payment.ProviderResult;
import com.softropic.payam.common.payment.SubscriberStatus;
import com.softropic.payam.mtn.config.MtnMoMoConfig;
import com.softropic.payam.mtn.contract.MtnCallbackPayload;
import com.softropic.payam.mtn.contract.dto.RequestToPayRequest;
import com.softropic.payam.mtn.contract.exception.MtnAccountInactiveException;
import com.softropic.payam.mtn.infrastructure.MtnMoMoClient;
import com.softropic.payam.transaction.contract.TransactionEventType;
import com.softropic.payam.transaction.contract.TransactionStatus;
import com.softropic.payam.transaction.repo.TransactionRepository;
import com.softropic.payam.transaction.service.EventLogService;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.github.resilience4j.retry.annotation.Retry;

import com.softropic.payam.webhook.contract.WebhookReceivedEvent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static net.logstash.logback.argument.StructuredArguments.kv;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.Duration;
import java.util.UUID;

@Service
public class MtnMoMoPort implements MobileMoneyPort {

    private static final Logger log = LoggerFactory.getLogger(MtnMoMoPort.class);

    private final MtnMoMoClient mtnMoMoClient;
    private final MtnTokenService mtnTokenService;
    private final TransactionRepository transactionRepository;
    private final EventLogService eventLogService;
    private final MtnMoMoConfig config;
    private final StringRedisTemplate redis;
    private final ApplicationEventPublisher eventPublisher;
    private final TransactionTemplate transactionTemplate;

    public MtnMoMoPort(MtnMoMoClient mtnMoMoClient,
                       MtnTokenService mtnTokenService,
                       TransactionRepository transactionRepository,
                       EventLogService eventLogService,
                       MtnMoMoConfig config,
                       StringRedisTemplate redis,
                       ApplicationEventPublisher eventPublisher,
                       TransactionTemplate transactionTemplate) {
        this.mtnMoMoClient = mtnMoMoClient;
        this.mtnTokenService = mtnTokenService;
        this.transactionRepository = transactionRepository;
        this.eventLogService = eventLogService;
        this.config = config;
        this.redis = redis;
        this.eventPublisher = eventPublisher;
        this.transactionTemplate = transactionTemplate;
    }

    /**
     * Implements MobileMoneyPort.initiateMerchantPayment.
     *
     * IMPORTANT (P1.1): This method is NOT @Transactional. The caller (TransactionService.initiate)
     * has already committed the INITIATED row before calling this method.
     *
     * IMPORTANT (Pitfall 6): referenceId is generated by us (merchant-generated UUID) and persisted
     * BEFORE the requestToPay API call, so that a crash after the call does not lose the providerRef.
     * This is the key difference from Orange (where providerRef comes back from the API).
     *
     * Flow: validate account -> generate UUID -> persistProviderRef (REQUIRES_NEW) -> requestToPay -> log event
     */
    @Override
    @CircuitBreaker(name = "mtn")
    @Retry(name = "mtn")
    public ProviderResult initiateMerchantPayment(PaymentCommand cmd) {
        String token = mtnTokenService.getAccessToken();

        // Step 1: Validate account holder
        try {
            mtnMoMoClient.validateAccountHolder(stripPlus(cmd.msisdn()), token);
        } catch (MtnAccountInactiveException e) {
            // Circuit breaker ignoreExceptions must include MtnAccountInactiveException
            throw e;
        }

        // Step 2: Generate referenceId (merchant-generated UUID for MTN)
        String referenceId = UUID.randomUUID().toString();

        // Step 3: Persist referenceId BEFORE API call (Pitfall 6 — crash-safe providerRef)
        persistProviderRef(cmd.transactionId(), referenceId);

        // Step 4: Build and send requestToPay
        RequestToPayRequest request = new RequestToPayRequest();
        request.setAmount(cmd.amount().toPlainString());
        request.setCurrency(cmd.currency());
        request.setExternalId(cmd.transactionId());
        request.setPayer(new RequestToPayRequest.Party("MSISDN", stripPlus(cmd.msisdn())));
        request.setPayerMessage("Payment via Payam");
        request.setPayeeNote(cmd.externalReference() != null ? cmd.externalReference() : cmd.transactionId());

        // Step 5: Call requestToPay — returns void on 202
        mtnMoMoClient.requestToPay(referenceId, request, token);

        // Step 6: Append event log (INITIATED -> PROCESSING)
        eventLogService.append(
            cmd.transactionId(), cmd.traceId(), cmd.externalReference(),
            TransactionEventType.PAYMENT_INITIATED,
            TransactionStatus.INITIATED, TransactionStatus.PROCESSING,
            "MTN_ADAPTER", null
        );

        // Step 7: Return pending result with the merchant-generated referenceId
        return ProviderResult.pending(referenceId, "PENDING");
    }

    /**
     * Implements MobileMoneyPort.getTransactionStatus.
     * Polls /collection/v1_0/requesttopay/{referenceId} and returns ProviderResult.
     */
    @Override
    @Transactional
    @CircuitBreaker(name = "mtn")
    public ProviderResult getTransactionStatus(String providerRef) {
        String token = mtnTokenService.getAccessToken();
        var response = mtnMoMoClient.getRequestToPayStatus(providerRef, token);
        String rawStatus = response.getStatus();
        TransactionStatus internal = MtnStatusMapper.toInternal(rawStatus);
        boolean pending = internal == TransactionStatus.PROCESSING;
        return pending
            ? ProviderResult.pending(providerRef, rawStatus)
            : ProviderResult.success(providerRef, rawStatus);
    }

    /**
     * Implements MobileMoneyPort.validateSubscriber.
     * Returns SubscriberStatus; active=false when MtnAccountInactiveException caught
     * (MTN returns 404 for inactive — no status field in body).
     */
    @Override
    public SubscriberStatus validateSubscriber(String msisdn) {
        String token = mtnTokenService.getAccessToken();
        try {
            mtnMoMoClient.validateAccountHolder(stripPlus(msisdn), token);
            return new SubscriberStatus(true, msisdn, "ACTIVE");
        } catch (MtnAccountInactiveException e) {
            return new SubscriberStatus(false, msisdn, "INACTIVE");
        }
    }

    /**
     * Public method for MtnCallbackController — NOT part of MobileMoneyPort interface.
     * Logs the callback and stores financialTransactionId for reconciliation.
     * Phase 6 wires full state-transition via double-check getTransactionStatus().
     */
    public void processCallback(MtnCallbackPayload payload) {
        // Dedup: one callback per (externalId, status) terminal event
        // MTN security note: no HMAC on inbound callbacks per MTN API contract.
        // Authenticity is provided by notifToken correlation + IP whitelist (MtnIpWhitelistInterceptor).
        String dedupKey = "webhook:mtn:" + payload.getExternalId() + ":" + payload.getStatus();
        Boolean wasAbsent = redis.opsForValue().setIfAbsent(dedupKey, "SEEN", Duration.ofHours(24));
        if (Boolean.FALSE.equals(wasAbsent)) {
            log.info("MTN callback duplicate suppressed",
                kv("operation", "webhook_received"),
                kv("provider", "MTN"),
                kv("externalId", payload.getExternalId()),
                kv("status", "DUPLICATE"));
            return;
        }

        log.info("Webhook received",
            kv("operation", "webhook_received"),
            kv("provider", "MTN"),
            kv("transactionId", payload.getExternalId()),
            kv("externalReference", payload.getFinancialTransactionId()),
            kv("providerStatus", payload.getStatus()));
        if (payload.getFinancialTransactionId() != null) {
            storeFinancialTxId(payload.getExternalId(), payload.getFinancialTransactionId());
        }

        // Look up Transaction by transactionId (= payload.getExternalId() for MTN)
        transactionRepository.findByTransactionId(payload.getExternalId()).ifPresent(tx -> {
            String providerRef = tx.getProviderRef(); // referenceId UUID stored by initiateMerchantPayment
            String txId = tx.getTransactionId();
            String traceId = tx.getTraceId();
            // Publish inside a transaction boundary so @TransactionalEventListener(AFTER_COMMIT) fires
            transactionTemplate.execute(status -> {
                eventPublisher.publishEvent(new WebhookReceivedEvent(
                    txId,
                    com.softropic.payam.common.payment.MobilePaymentProvider.MTN,
                    providerRef,
                    traceId
                ));
                return null;
            });
        });
    }

    // ---- private helpers ----

    /**
     * Strip leading '+' from MSISDN for MTN endpoints.
     * MTN accepts full country code without '+'.
     * "+237692954629" -> "237692954629"
     * "237692954629"  -> "237692954629" (already without plus)
     */
    private String stripPlus(String msisdn) {
        if (msisdn == null) return null;
        return msisdn.startsWith("+") ? msisdn.substring(1) : msisdn;
    }

    /**
     * Persist providerRef (referenceId) to the Transaction record BEFORE the API call.
     * Uses TransactionTemplate directly (not @Transactional) because this method is called via
     * self-invocation (this.persistProviderRef), which bypasses the Spring AOP proxy and makes
     * @Transactional a no-op. TransactionTemplate creates a real transaction so that
     * findByTransactionIdForUpdate can acquire the pessimistic write lock (Pitfall 6).
     */
    protected void persistProviderRef(String transactionId, String providerRef) {
        transactionTemplate.execute(status -> {
            transactionRepository.findByTransactionIdForUpdate(transactionId).ifPresent(tx -> {
                tx.setProviderRef(providerRef);
                transactionRepository.save(tx);
            });
            return null;
        });
    }

    /**
     * Store MTN financialTransactionId on the Transaction for reconciliation.
     * Uses REQUIRES_NEW so this is committed immediately when the callback arrives.
     */
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    protected void storeFinancialTxId(String transactionId, String financialTxId) {
        transactionRepository.findByTransactionId(transactionId).ifPresent(tx -> {
            tx.setMtnFinancialTxId(financialTxId);
            transactionRepository.save(tx);
        });
    }

    // No fallback methods — circuit-open throws CallNotPermittedException to caller.
    // Phase 5 (PaymentOrchestrator) handles circuit state at the orchestration level.
}
