-- V31: Transaction-Backed Disbursements — Schema Migration
-- (1) Pre-flight: refuse to run if any in-flight (PROCESSING / PENDING_CONFIRMATION)
--     disbursement exists. Operators MUST drain live traffic first.
-- (2) Add admin_note (TEXT) + retry_count (INT NOT NULL DEFAULT 0) to disbursement + _aud
-- (3) Drop reserved_amount from disbursement + _aud (wallet model retired at app layer)
-- (4) Create disbursement_transaction_ref_aud (Envers) and disbursement_transaction_ref base
-- (5) Partial unique index enforces TXN-03: one ACTIVE (PENDING/CLAIMED) claim per
--     transaction_id at the database layer. RELEASED rows are excluded so retry
--     reactivation (IDEM-02) preserves audit trail without index conflict.

-- ============================================================
-- Step 1: Pre-flight — refuse to migrate while disbursements are in flight
-- ============================================================
DO $$
DECLARE
    bad_count INT;
BEGIN
    SELECT COUNT(*) INTO bad_count
    FROM main.disbursement
    WHERE disbursement_status IN ('PROCESSING', 'PENDING_CONFIRMATION');
    IF bad_count > 0 THEN
        RAISE EXCEPTION 'V31 pre-flight: % disbursement(s) in PROCESSING or PENDING_CONFIRMATION — drain live traffic before running this migration', bad_count;
    END IF;
END $$;

-- ============================================================
-- Step 2: Add admin_note + retry_count columns to disbursement + _aud
-- admin_note: nullable TEXT, populated by Phase 56 admin-approval flow
-- retry_count: NOT NULL DEFAULT 0, incremented by Phase 57 IDEM-02 retry recovery
-- ============================================================
ALTER TABLE main.disbursement
    ADD COLUMN IF NOT EXISTS admin_note TEXT,
    ADD COLUMN IF NOT EXISTS retry_count INT NOT NULL DEFAULT 0;

-- _aud: all audited columns are nullable (Envers convention) — no DEFAULT here
ALTER TABLE main.disbursement_aud
    ADD COLUMN IF NOT EXISTS admin_note TEXT,
    ADD COLUMN IF NOT EXISTS retry_count INT;

-- ============================================================
-- Step 3: Drop reserved_amount from disbursement + _aud
-- Safe because all existing rows have reserved_amount NULL or 0 (v10 invariant);
-- the entity-side mapping is removed in Plan 03 of Phase 54 — startup-time
-- Hibernate schema validation between this migration and Plan 03's entity edit will fail,
-- which is why Plan 03's first task removes the field before any test reboots context.
-- ============================================================
ALTER TABLE main.disbursement DROP COLUMN IF EXISTS reserved_amount;
ALTER TABLE main.disbursement_aud DROP COLUMN IF EXISTS reserved_amount;

-- ============================================================
-- Step 4a: Envers audit table (created BEFORE base table — V28 pattern)
-- All audited columns nullable; PK is composite (id, rev).
-- ============================================================
CREATE TABLE IF NOT EXISTS main.disbursement_transaction_ref_aud (
    id                 BIGINT      NOT NULL,
    rev                INTEGER     NOT NULL REFERENCES main.revinfo(rev),
    revtype            SMALLINT,
    disbursement_id    BIGINT,
    transaction_id     VARCHAR(36),
    ref_status         VARCHAR(30),
    status             VARCHAR(20),
    created_by         VARCHAR(50),
    created_date       TIMESTAMP,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP,
    request_id         VARCHAR(255),
    session_id         TEXT,
    PRIMARY KEY (id, rev)
);

-- ============================================================
-- Step 4b: Base table — disbursement_transaction_ref
-- id: BIGINT PK (TSID-generated by Hibernate)
-- disbursement_id: BIGINT, references main.disbursement(id) (NOT enforced as DB FK
--     for performance consistency with ledger_entry — see RESEARCH "Anti-Patterns to Avoid")
-- transaction_id: VARCHAR(36) — logical UUID on main.transaction.transaction_id
--     (matches ledger_entry.transaction_id convention; no DB FK)
-- ref_status: VARCHAR(30) — DisbursementRefStatus enum stored as STRING
-- status: EntityStatus from AbstractAuditingEntity (NOT NULL DEFAULT 'ACTIVE')
-- ============================================================
CREATE TABLE IF NOT EXISTS main.disbursement_transaction_ref (
    id                 BIGINT      NOT NULL,
    disbursement_id    BIGINT      NOT NULL,
    transaction_id     VARCHAR(36) NOT NULL,
    ref_status         VARCHAR(30) NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by         VARCHAR(50),
    created_date       TIMESTAMP,
    last_modified_by   VARCHAR(50),
    last_modified_date TIMESTAMP,
    request_id         VARCHAR(255),
    session_id         TEXT,
    CONSTRAINT pk_disbursement_transaction_ref PRIMARY KEY (id)
);

-- Index for lookup by disbursement_id (used by IDEM-02 retry reactivation in Phase 57)
CREATE INDEX IF NOT EXISTS idx_dtr_disbursement_id
    ON main.disbursement_transaction_ref (disbursement_id);

-- ============================================================
-- Step 5: Partial unique index — TXN-03 at the DB layer
-- A second INSERT for the same transaction_id with ref_status IN ('PENDING','CLAIMED')
-- is rejected with a unique-constraint violation. RELEASED rows are excluded from the
-- predicate so retry reactivation (IDEM-02) and audit history both work without conflict.
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS uq_dtr_txn_active_claim
    ON main.disbursement_transaction_ref (transaction_id)
    WHERE ref_status IN ('PENDING', 'CLAIMED');

COMMENT ON COLUMN main.disbursement.admin_note IS
    'Phase 56 ADMIN-02: free-text note populated when a disbursement requires admin approval. Never returned in public merchant API.';
COMMENT ON COLUMN main.disbursement.retry_count IS
    'Phase 57 IDEM-02: number of times this disbursement has been retried via the same Idempotency-Key. Incremented on each successful retry-validation.';
